// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE8k24-sUPgReQ90LhFaYLJXUxKIoT8m0',
    appId: '1:1094525773604:web:a57bc93c358a060cff35b1',
    messagingSenderId: '1094525773604',
    projectId: 'flutterlab-firebase-b9c6f',
    authDomain: 'flutterlab-firebase-b9c6f.firebaseapp.com',
    storageBucket: 'flutterlab-firebase-b9c6f.appspot.com',
    measurementId: 'G-FJLBTP7RSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBcIbP-mNfgSTJIy6iTzaEWzUfb2mBgq8',
    appId: '1:1094525773604:android:1eb696165cc52f43ff35b1',
    messagingSenderId: '1094525773604',
    projectId: 'flutterlab-firebase-b9c6f',
    storageBucket: 'flutterlab-firebase-b9c6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8OL8tIVdOYXvFabldx71s6M860Qs5RaU',
    appId: '1:1094525773604:ios:8b4cae4430aa1a1fff35b1',
    messagingSenderId: '1094525773604',
    projectId: 'flutterlab-firebase-b9c6f',
    storageBucket: 'flutterlab-firebase-b9c6f.appspot.com',
    iosClientId: '1094525773604-71fdf8hr9rk7oohv0n5du045fpa1t5qp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8OL8tIVdOYXvFabldx71s6M860Qs5RaU',
    appId: '1:1094525773604:ios:8b4cae4430aa1a1fff35b1',
    messagingSenderId: '1094525773604',
    projectId: 'flutterlab-firebase-b9c6f',
    storageBucket: 'flutterlab-firebase-b9c6f.appspot.com',
    iosClientId: '1094525773604-71fdf8hr9rk7oohv0n5du045fpa1t5qp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );
}
